//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypOnEF.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PetsPlanetDBContext : DbContext
    {
        public PetsPlanetDBContext()
            : base("name=PetsPlanetDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Pets_Warehouse> Pets_Warehouses { get; set; }
        public virtual DbSet<Pets_C1> Pets_C1 { get; set; }
        public virtual DbSet<Pets_C2> Pets_C2 { get; set; }
        public virtual DbSet<Pets_C3> Pets_C3 { get; set; }
        public virtual DbSet<Pets_Image> Pets_Image { get; set; }
        public virtual DbSet<Pets_Inventory> Pets_Inventory { get; set; }
        public virtual DbSet<Product_C1> Product_C1 { get; set; }
        public virtual DbSet<Product_C2> Product_C2 { get; set; }
        public virtual DbSet<Product_C3> Product_C3 { get; set; }
        public virtual DbSet<Product_Image> Product_Image { get; set; }
        public virtual DbSet<Product_Inventory> Product_Inventory { get; set; }
        public virtual DbSet<Product_Inverntory_Sales> Product_Inverntory_Sales { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User_Info> User_Info { get; set; }
        public virtual DbSet<User_Type> User_Type { get; set; }
        public virtual DbSet<Vendor_Product> Vendor_Products { get; set; }
        public virtual DbSet<Vendor_Product_Qty> Vendor_Product_Qties { get; set; }
        public virtual DbSet<Vendor_Image> Vendor_Image { get; set; }
        public virtual DbSet<Vendor_Info> Vendor_Info { get; set; }
        public virtual DbSet<Vendor_Product_Cost> Vendor_Product_Cost { get; set; }
    
        public virtual int AddnewProductCat_1(string pC1_Name)
        {
            var pC1_NameParameter = pC1_Name != null ?
                new ObjectParameter("PC1_Name", pC1_Name) :
                new ObjectParameter("PC1_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddnewProductCat_1", pC1_NameParameter);
        }
    
        public virtual int AddnewProductCat_2(string pC2_Name)
        {
            var pC2_NameParameter = pC2_Name != null ?
                new ObjectParameter("PC2_Name", pC2_Name) :
                new ObjectParameter("PC2_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddnewProductCat_2", pC2_NameParameter);
        }
    
        public virtual ObjectResult<AllBlogView_Result> AllBlogView()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllBlogView_Result>("AllBlogView");
        }
    
        public virtual int ApproveBlog(Nullable<int> blog_Id)
        {
            var blog_IdParameter = blog_Id.HasValue ?
                new ObjectParameter("Blog_Id", blog_Id) :
                new ObjectParameter("Blog_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ApproveBlog", blog_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ApproveProduct(Nullable<int> pC3_Id)
        {
            var pC3_IdParameter = pC3_Id.HasValue ?
                new ObjectParameter("PC3_Id", pC3_Id) :
                new ObjectParameter("PC3_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ApproveProduct", pC3_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ApprovVendor(Nullable<int> vI_Id)
        {
            var vI_IdParameter = vI_Id.HasValue ?
                new ObjectParameter("VI_Id", vI_Id) :
                new ObjectParameter("VI_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ApprovVendor", vI_IdParameter);
        }
    
        public virtual ObjectResult<BlogDetailsGet_Result> BlogDetailsGet(Nullable<int> blog_Id)
        {
            var blog_IdParameter = blog_Id.HasValue ?
                new ObjectParameter("Blog_Id", blog_Id) :
                new ObjectParameter("Blog_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BlogDetailsGet_Result>("BlogDetailsGet", blog_IdParameter);
        }
    
        public virtual ObjectResult<BlogDisplay_Result> BlogDisplay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BlogDisplay_Result>("BlogDisplay");
        }
    
        public virtual int BlogUploading(string uS_Name, string blog_Title, string blog_Date, string blogger_PicturePath, string blog_PicturePath, string blog_WholeBlog, string blogger_PictureName, string blog_PictureName)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            var blog_TitleParameter = blog_Title != null ?
                new ObjectParameter("Blog_Title", blog_Title) :
                new ObjectParameter("Blog_Title", typeof(string));
    
            var blog_DateParameter = blog_Date != null ?
                new ObjectParameter("Blog_Date", blog_Date) :
                new ObjectParameter("Blog_Date", typeof(string));
    
            var blogger_PicturePathParameter = blogger_PicturePath != null ?
                new ObjectParameter("Blogger_PicturePath", blogger_PicturePath) :
                new ObjectParameter("Blogger_PicturePath", typeof(string));
    
            var blog_PicturePathParameter = blog_PicturePath != null ?
                new ObjectParameter("Blog_PicturePath", blog_PicturePath) :
                new ObjectParameter("Blog_PicturePath", typeof(string));
    
            var blog_WholeBlogParameter = blog_WholeBlog != null ?
                new ObjectParameter("Blog_WholeBlog", blog_WholeBlog) :
                new ObjectParameter("Blog_WholeBlog", typeof(string));
    
            var blogger_PictureNameParameter = blogger_PictureName != null ?
                new ObjectParameter("Blogger_PictureName", blogger_PictureName) :
                new ObjectParameter("Blogger_PictureName", typeof(string));
    
            var blog_PictureNameParameter = blog_PictureName != null ?
                new ObjectParameter("Blog_PictureName", blog_PictureName) :
                new ObjectParameter("Blog_PictureName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BlogUploading", uS_NameParameter, blog_TitleParameter, blog_DateParameter, blogger_PicturePathParameter, blog_PicturePathParameter, blog_WholeBlogParameter, blogger_PictureNameParameter, blog_PictureNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CheckUserIsAdmin(string uS_Name)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CheckUserIsAdmin", uS_NameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CheckUserIsBuyerSeller(string uS_Name)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CheckUserIsBuyerSeller", uS_NameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CheckUserIsVendor(string uS_Name)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CheckUserIsVendor", uS_NameParameter);
        }
    
        public virtual int DeleteBlog(Nullable<int> blog_Id)
        {
            var blog_IdParameter = blog_Id.HasValue ?
                new ObjectParameter("Blog_Id", blog_Id) :
                new ObjectParameter("Blog_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteBlog", blog_IdParameter);
        }
    
        public virtual int DeleteVendor(Nullable<int> vI_Id)
        {
            var vI_IdParameter = vI_Id.HasValue ?
                new ObjectParameter("VI_Id", vI_Id) :
                new ObjectParameter("VI_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteVendor", vI_IdParameter);
        }
    
        public virtual int DeleteVendorProduct(Nullable<int> pC3_Id)
        {
            var pC3_IdParameter = pC3_Id.HasValue ?
                new ObjectParameter("PC3_Id", pC3_Id) :
                new ObjectParameter("PC3_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteVendorProduct", pC3_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> EmailVerification(string uS_ConfirmCode)
        {
            var uS_ConfirmCodeParameter = uS_ConfirmCode != null ?
                new ObjectParameter("US_ConfirmCode", uS_ConfirmCode) :
                new ObjectParameter("US_ConfirmCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("EmailVerification", uS_ConfirmCodeParameter);
        }
    
        public virtual ObjectResult<GetApproveBlogs_Result> GetApproveBlogs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetApproveBlogs_Result>("GetApproveBlogs");
        }
    
        public virtual ObjectResult<GetApproveVendor_Result> GetApproveVendor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetApproveVendor_Result>("GetApproveVendor");
        }
    
        public virtual ObjectResult<GetApproveVendorProducts_Result> GetApproveVendorProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetApproveVendorProducts_Result>("GetApproveVendorProducts");
        }
    
        public virtual ObjectResult<GetCustomRoles_Result> GetCustomRoles(string u_Type)
        {
            var u_TypeParameter = u_Type != null ?
                new ObjectParameter("U_Type", u_Type) :
                new ObjectParameter("U_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomRoles_Result>("GetCustomRoles", u_TypeParameter);
        }
    
        public virtual ObjectResult<GetNewBlogs_Result> GetNewBlogs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNewBlogs_Result>("GetNewBlogs");
        }
    
        public virtual ObjectResult<GetNewProducts_Result> GetNewProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNewProducts_Result>("GetNewProducts");
        }
    
        public virtual ObjectResult<GetNewVendor_Result> GetNewVendor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNewVendor_Result>("GetNewVendor");
        }
    
        public virtual ObjectResult<GetNotApproveBlogs_Result> GetNotApproveBlogs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNotApproveBlogs_Result>("GetNotApproveBlogs");
        }
    
        public virtual ObjectResult<GetNotApproveVendor_Result> GetNotApproveVendor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNotApproveVendor_Result>("GetNotApproveVendor");
        }
    
        public virtual ObjectResult<GetNotApproveVendorProducts_Result> GetNotApproveVendorProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNotApproveVendorProducts_Result>("GetNotApproveVendorProducts");
        }
    
        public virtual ObjectResult<GetProductCart_Result> GetProductCart(Nullable<int> pC3_Id)
        {
            var pC3_IdParameter = pC3_Id.HasValue ?
                new ObjectParameter("PC3_Id", pC3_Id) :
                new ObjectParameter("PC3_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductCart_Result>("GetProductCart", pC3_IdParameter);
        }
    
        public virtual int NotApproveBlog(Nullable<int> blog_Id)
        {
            var blog_IdParameter = blog_Id.HasValue ?
                new ObjectParameter("Blog_Id", blog_Id) :
                new ObjectParameter("Blog_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NotApproveBlog", blog_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> NotApproveProduct(Nullable<int> pC3_Id)
        {
            var pC3_IdParameter = pC3_Id.HasValue ?
                new ObjectParameter("PC3_Id", pC3_Id) :
                new ObjectParameter("PC3_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NotApproveProduct", pC3_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> NotApprovVendor(Nullable<int> vI_Id)
        {
            var vI_IdParameter = vI_Id.HasValue ?
                new ObjectParameter("VI_Id", vI_Id) :
                new ObjectParameter("VI_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NotApprovVendor", vI_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Order(string uS_Name, string deliveryAddress, string phone1, string phone2, Nullable<decimal> totalPrice, Nullable<int> totalitem, Nullable<int> pC3_Id, Nullable<int> qty)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            var deliveryAddressParameter = deliveryAddress != null ?
                new ObjectParameter("DeliveryAddress", deliveryAddress) :
                new ObjectParameter("DeliveryAddress", typeof(string));
    
            var phone1Parameter = phone1 != null ?
                new ObjectParameter("Phone1", phone1) :
                new ObjectParameter("Phone1", typeof(string));
    
            var phone2Parameter = phone2 != null ?
                new ObjectParameter("Phone2", phone2) :
                new ObjectParameter("Phone2", typeof(string));
    
            var totalPriceParameter = totalPrice.HasValue ?
                new ObjectParameter("TotalPrice", totalPrice) :
                new ObjectParameter("TotalPrice", typeof(decimal));
    
            var totalitemParameter = totalitem.HasValue ?
                new ObjectParameter("Totalitem", totalitem) :
                new ObjectParameter("Totalitem", typeof(int));
    
            var pC3_IdParameter = pC3_Id.HasValue ?
                new ObjectParameter("PC3_Id", pC3_Id) :
                new ObjectParameter("PC3_Id", typeof(int));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("Qty", qty) :
                new ObjectParameter("Qty", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Order", uS_NameParameter, deliveryAddressParameter, phone1Parameter, phone2Parameter, totalPriceParameter, totalitemParameter, pC3_IdParameter, qtyParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> PetsInfo(string petsC1_Name, string petsC2_Name, string petsC3_Name)
        {
            var petsC1_NameParameter = petsC1_Name != null ?
                new ObjectParameter("PetsC1_Name", petsC1_Name) :
                new ObjectParameter("PetsC1_Name", typeof(string));
    
            var petsC2_NameParameter = petsC2_Name != null ?
                new ObjectParameter("PetsC2_Name", petsC2_Name) :
                new ObjectParameter("PetsC2_Name", typeof(string));
    
            var petsC3_NameParameter = petsC3_Name != null ?
                new ObjectParameter("PetsC3_Name", petsC3_Name) :
                new ObjectParameter("PetsC3_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("PetsInfo", petsC1_NameParameter, petsC2_NameParameter, petsC3_NameParameter);
        }
    
        public virtual ObjectResult<PetsPanelView_Result> PetsPanelView()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PetsPanelView_Result>("PetsPanelView");
        }
    
        public virtual ObjectResult<ProductDetailsGet_Result> ProductDetailsGet(Nullable<int> pC3_Id)
        {
            var pC3_IdParameter = pC3_Id.HasValue ?
                new ObjectParameter("PC3_Id", pC3_Id) :
                new ObjectParameter("PC3_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductDetailsGet_Result>("ProductDetailsGet", pC3_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> ProductInfo(string pC1_Id, string pC2_Name, string pC3_Name)
        {
            var pC1_IdParameter = pC1_Id != null ?
                new ObjectParameter("PC1_Id", pC1_Id) :
                new ObjectParameter("PC1_Id", typeof(string));
    
            var pC2_NameParameter = pC2_Name != null ?
                new ObjectParameter("PC2_Name", pC2_Name) :
                new ObjectParameter("PC2_Name", typeof(string));
    
            var pC3_NameParameter = pC3_Name != null ?
                new ObjectParameter("PC3_Name", pC3_Name) :
                new ObjectParameter("PC3_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("ProductInfo", pC1_IdParameter, pC2_NameParameter, pC3_NameParameter);
        }
    
        public virtual ObjectResult<ProductPanelView_Result> ProductPanelView()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductPanelView_Result>("ProductPanelView");
        }
    
        public virtual ObjectResult<ProductSearch_Result> ProductSearch(string proSearch)
        {
            var proSearchParameter = proSearch != null ?
                new ObjectParameter("ProSearch", proSearch) :
                new ObjectParameter("ProSearch", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductSearch_Result>("ProductSearch", proSearchParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> RegisterAdmin(string uS_Name, string uS_Phone, string uS_Address, string uS_Email, string uS_Password, string uS_ConfirmCode)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            var uS_PhoneParameter = uS_Phone != null ?
                new ObjectParameter("US_Phone", uS_Phone) :
                new ObjectParameter("US_Phone", typeof(string));
    
            var uS_AddressParameter = uS_Address != null ?
                new ObjectParameter("US_Address", uS_Address) :
                new ObjectParameter("US_Address", typeof(string));
    
            var uS_EmailParameter = uS_Email != null ?
                new ObjectParameter("US_Email", uS_Email) :
                new ObjectParameter("US_Email", typeof(string));
    
            var uS_PasswordParameter = uS_Password != null ?
                new ObjectParameter("US_Password", uS_Password) :
                new ObjectParameter("US_Password", typeof(string));
    
            var uS_ConfirmCodeParameter = uS_ConfirmCode != null ?
                new ObjectParameter("US_ConfirmCode", uS_ConfirmCode) :
                new ObjectParameter("US_ConfirmCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("RegisterAdmin", uS_NameParameter, uS_PhoneParameter, uS_AddressParameter, uS_EmailParameter, uS_PasswordParameter, uS_ConfirmCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> RegisterBuyerSeller(string uS_Name, string uS_Phone, string uS_Address, string uS_Email, string uS_Password, string uS_ConfirmCode)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            var uS_PhoneParameter = uS_Phone != null ?
                new ObjectParameter("US_Phone", uS_Phone) :
                new ObjectParameter("US_Phone", typeof(string));
    
            var uS_AddressParameter = uS_Address != null ?
                new ObjectParameter("US_Address", uS_Address) :
                new ObjectParameter("US_Address", typeof(string));
    
            var uS_EmailParameter = uS_Email != null ?
                new ObjectParameter("US_Email", uS_Email) :
                new ObjectParameter("US_Email", typeof(string));
    
            var uS_PasswordParameter = uS_Password != null ?
                new ObjectParameter("US_Password", uS_Password) :
                new ObjectParameter("US_Password", typeof(string));
    
            var uS_ConfirmCodeParameter = uS_ConfirmCode != null ?
                new ObjectParameter("US_ConfirmCode", uS_ConfirmCode) :
                new ObjectParameter("US_ConfirmCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("RegisterBuyerSeller", uS_NameParameter, uS_PhoneParameter, uS_AddressParameter, uS_EmailParameter, uS_PasswordParameter, uS_ConfirmCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> RegisterVendor(string uS_Name, string uS_Phone, string uS_Address, string uS_Email, string uS_Password, string vI_CNIC, string vI_Province, string vI_City, string uS_ConfirmCode, string vendorImage_ImagePath, string vendorImage_Name)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            var uS_PhoneParameter = uS_Phone != null ?
                new ObjectParameter("US_Phone", uS_Phone) :
                new ObjectParameter("US_Phone", typeof(string));
    
            var uS_AddressParameter = uS_Address != null ?
                new ObjectParameter("US_Address", uS_Address) :
                new ObjectParameter("US_Address", typeof(string));
    
            var uS_EmailParameter = uS_Email != null ?
                new ObjectParameter("US_Email", uS_Email) :
                new ObjectParameter("US_Email", typeof(string));
    
            var uS_PasswordParameter = uS_Password != null ?
                new ObjectParameter("US_Password", uS_Password) :
                new ObjectParameter("US_Password", typeof(string));
    
            var vI_CNICParameter = vI_CNIC != null ?
                new ObjectParameter("VI_CNIC", vI_CNIC) :
                new ObjectParameter("VI_CNIC", typeof(string));
    
            var vI_ProvinceParameter = vI_Province != null ?
                new ObjectParameter("VI_Province", vI_Province) :
                new ObjectParameter("VI_Province", typeof(string));
    
            var vI_CityParameter = vI_City != null ?
                new ObjectParameter("VI_City", vI_City) :
                new ObjectParameter("VI_City", typeof(string));
    
            var uS_ConfirmCodeParameter = uS_ConfirmCode != null ?
                new ObjectParameter("US_ConfirmCode", uS_ConfirmCode) :
                new ObjectParameter("US_ConfirmCode", typeof(string));
    
            var vendorImage_ImagePathParameter = vendorImage_ImagePath != null ?
                new ObjectParameter("VendorImage_ImagePath", vendorImage_ImagePath) :
                new ObjectParameter("VendorImage_ImagePath", typeof(string));
    
            var vendorImage_NameParameter = vendorImage_Name != null ?
                new ObjectParameter("VendorImage_Name", vendorImage_Name) :
                new ObjectParameter("VendorImage_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("RegisterVendor", uS_NameParameter, uS_PhoneParameter, uS_AddressParameter, uS_EmailParameter, uS_PasswordParameter, vI_CNICParameter, vI_ProvinceParameter, vI_CityParameter, uS_ConfirmCodeParameter, vendorImage_ImagePathParameter, vendorImage_NameParameter);
        }
    
        public virtual ObjectResult<SearchProduct_Result> SearchProduct(string pC3_Name)
        {
            var pC3_NameParameter = pC3_Name != null ?
                new ObjectParameter("PC3_Name", pC3_Name) :
                new ObjectParameter("PC3_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchProduct_Result>("SearchProduct", pC3_NameParameter);
        }
    
        public virtual ObjectResult<SelectedPetDetails_Result> SelectedPetDetails(Nullable<int> petsC3_Id)
        {
            var petsC3_IdParameter = petsC3_Id.HasValue ?
                new ObjectParameter("PetsC3_Id", petsC3_Id) :
                new ObjectParameter("PetsC3_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectedPetDetails_Result>("SelectedPetDetails", petsC3_IdParameter);
        }
    
        public virtual ObjectResult<SelectedProductDeatils_Result> SelectedProductDeatils(Nullable<int> pC3_Id)
        {
            var pC3_IdParameter = pC3_Id.HasValue ?
                new ObjectParameter("PC3_Id", pC3_Id) :
                new ObjectParameter("PC3_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectedProductDeatils_Result>("SelectedProductDeatils", pC3_IdParameter);
        }
    
        public virtual ObjectResult<SelectProductInfo_Result> SelectProductInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectProductInfo_Result>("SelectProductInfo");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int UpdateProduct(Nullable<int> oldProductId, Nullable<int> pC1_Id, Nullable<int> pC2_Id, string pC3_Name, string vP_Desc, string vP_Specs, Nullable<int> vPQ_Qty, Nullable<int> vendor_Price, Nullable<int> company_Price, string proImg_Path, string proImg_Name, Nullable<int> proImgId)
        {
            var oldProductIdParameter = oldProductId.HasValue ?
                new ObjectParameter("OldProductId", oldProductId) :
                new ObjectParameter("OldProductId", typeof(int));
    
            var pC1_IdParameter = pC1_Id.HasValue ?
                new ObjectParameter("PC1_Id", pC1_Id) :
                new ObjectParameter("PC1_Id", typeof(int));
    
            var pC2_IdParameter = pC2_Id.HasValue ?
                new ObjectParameter("PC2_Id", pC2_Id) :
                new ObjectParameter("PC2_Id", typeof(int));
    
            var pC3_NameParameter = pC3_Name != null ?
                new ObjectParameter("PC3_Name", pC3_Name) :
                new ObjectParameter("PC3_Name", typeof(string));
    
            var vP_DescParameter = vP_Desc != null ?
                new ObjectParameter("VP_Desc", vP_Desc) :
                new ObjectParameter("VP_Desc", typeof(string));
    
            var vP_SpecsParameter = vP_Specs != null ?
                new ObjectParameter("VP_Specs", vP_Specs) :
                new ObjectParameter("VP_Specs", typeof(string));
    
            var vPQ_QtyParameter = vPQ_Qty.HasValue ?
                new ObjectParameter("VPQ_Qty", vPQ_Qty) :
                new ObjectParameter("VPQ_Qty", typeof(int));
    
            var vendor_PriceParameter = vendor_Price.HasValue ?
                new ObjectParameter("Vendor_Price", vendor_Price) :
                new ObjectParameter("Vendor_Price", typeof(int));
    
            var company_PriceParameter = company_Price.HasValue ?
                new ObjectParameter("Company_Price", company_Price) :
                new ObjectParameter("Company_Price", typeof(int));
    
            var proImg_PathParameter = proImg_Path != null ?
                new ObjectParameter("ProImg_Path", proImg_Path) :
                new ObjectParameter("ProImg_Path", typeof(string));
    
            var proImg_NameParameter = proImg_Name != null ?
                new ObjectParameter("ProImg_Name", proImg_Name) :
                new ObjectParameter("ProImg_Name", typeof(string));
    
            var proImgIdParameter = proImgId.HasValue ?
                new ObjectParameter("ProImgId", proImgId) :
                new ObjectParameter("ProImgId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateProduct", oldProductIdParameter, pC1_IdParameter, pC2_IdParameter, pC3_NameParameter, vP_DescParameter, vP_SpecsParameter, vPQ_QtyParameter, vendor_PriceParameter, company_PriceParameter, proImg_PathParameter, proImg_NameParameter, proImgIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UserLogin(string uS_Name, string uS_Password)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            var uS_PasswordParameter = uS_Password != null ?
                new ObjectParameter("US_Password", uS_Password) :
                new ObjectParameter("US_Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UserLogin", uS_NameParameter, uS_PasswordParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> UserPetsEntry(string uS_Name, Nullable<int> petsC1_Id, Nullable<int> petsC2_Id, string petsC3_Name, string descrption, Nullable<int> cost, string petsImage_Path, string petsImage_Name)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            var petsC1_IdParameter = petsC1_Id.HasValue ?
                new ObjectParameter("PetsC1_Id", petsC1_Id) :
                new ObjectParameter("PetsC1_Id", typeof(int));
    
            var petsC2_IdParameter = petsC2_Id.HasValue ?
                new ObjectParameter("PetsC2_Id", petsC2_Id) :
                new ObjectParameter("PetsC2_Id", typeof(int));
    
            var petsC3_NameParameter = petsC3_Name != null ?
                new ObjectParameter("PetsC3_Name", petsC3_Name) :
                new ObjectParameter("PetsC3_Name", typeof(string));
    
            var descrptionParameter = descrption != null ?
                new ObjectParameter("Descrption", descrption) :
                new ObjectParameter("Descrption", typeof(string));
    
            var costParameter = cost.HasValue ?
                new ObjectParameter("Cost", cost) :
                new ObjectParameter("Cost", typeof(int));
    
            var petsImage_PathParameter = petsImage_Path != null ?
                new ObjectParameter("PetsImage_Path", petsImage_Path) :
                new ObjectParameter("PetsImage_Path", typeof(string));
    
            var petsImage_NameParameter = petsImage_Name != null ?
                new ObjectParameter("PetsImage_Name", petsImage_Name) :
                new ObjectParameter("PetsImage_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("UserPetsEntry", uS_NameParameter, petsC1_IdParameter, petsC2_IdParameter, petsC3_NameParameter, descrptionParameter, costParameter, petsImage_PathParameter, petsImage_NameParameter);
        }
    
        public virtual int VendorCommission(Nullable<int> vI_Id, Nullable<double> vI_Commission)
        {
            var vI_IdParameter = vI_Id.HasValue ?
                new ObjectParameter("VI_Id", vI_Id) :
                new ObjectParameter("VI_Id", typeof(int));
    
            var vI_CommissionParameter = vI_Commission.HasValue ?
                new ObjectParameter("VI_Commission", vI_Commission) :
                new ObjectParameter("VI_Commission", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VendorCommission", vI_IdParameter, vI_CommissionParameter);
        }
    
        public virtual ObjectResult<VendorDetails_Result> VendorDetails(Nullable<int> vI_Id)
        {
            var vI_IdParameter = vI_Id.HasValue ?
                new ObjectParameter("VI_Id", vI_Id) :
                new ObjectParameter("VI_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VendorDetails_Result>("VendorDetails", vI_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> VendorProductEntry(string uS_Name, string pC1_Id, string pC2_Id, string pC3_Name, string proImg_Path, string proImg_Name, string vP_Desc, string vP_Specs, Nullable<int> vPQ_Qty, Nullable<int> vPQ_Status, Nullable<decimal> vendor_Price, Nullable<decimal> company_Price)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            var pC1_IdParameter = pC1_Id != null ?
                new ObjectParameter("PC1_Id", pC1_Id) :
                new ObjectParameter("PC1_Id", typeof(string));
    
            var pC2_IdParameter = pC2_Id != null ?
                new ObjectParameter("PC2_Id", pC2_Id) :
                new ObjectParameter("PC2_Id", typeof(string));
    
            var pC3_NameParameter = pC3_Name != null ?
                new ObjectParameter("PC3_Name", pC3_Name) :
                new ObjectParameter("PC3_Name", typeof(string));
    
            var proImg_PathParameter = proImg_Path != null ?
                new ObjectParameter("ProImg_Path", proImg_Path) :
                new ObjectParameter("ProImg_Path", typeof(string));
    
            var proImg_NameParameter = proImg_Name != null ?
                new ObjectParameter("ProImg_Name", proImg_Name) :
                new ObjectParameter("ProImg_Name", typeof(string));
    
            var vP_DescParameter = vP_Desc != null ?
                new ObjectParameter("VP_Desc", vP_Desc) :
                new ObjectParameter("VP_Desc", typeof(string));
    
            var vP_SpecsParameter = vP_Specs != null ?
                new ObjectParameter("VP_Specs", vP_Specs) :
                new ObjectParameter("VP_Specs", typeof(string));
    
            var vPQ_QtyParameter = vPQ_Qty.HasValue ?
                new ObjectParameter("VPQ_Qty", vPQ_Qty) :
                new ObjectParameter("VPQ_Qty", typeof(int));
    
            var vPQ_StatusParameter = vPQ_Status.HasValue ?
                new ObjectParameter("VPQ_Status", vPQ_Status) :
                new ObjectParameter("VPQ_Status", typeof(int));
    
            var vendor_PriceParameter = vendor_Price.HasValue ?
                new ObjectParameter("Vendor_Price", vendor_Price) :
                new ObjectParameter("Vendor_Price", typeof(decimal));
    
            var company_PriceParameter = company_Price.HasValue ?
                new ObjectParameter("Company_Price", company_Price) :
                new ObjectParameter("Company_Price", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("VendorProductEntry", uS_NameParameter, pC1_IdParameter, pC2_IdParameter, pC3_NameParameter, proImg_PathParameter, proImg_NameParameter, vP_DescParameter, vP_SpecsParameter, vPQ_QtyParameter, vPQ_StatusParameter, vendor_PriceParameter, company_PriceParameter);
        }
    
        public virtual ObjectResult<GetCustomerDistinctOrders_Result> GetCustomerDistinctOrders(string uS_Name)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerDistinctOrders_Result>("GetCustomerDistinctOrders", uS_NameParameter);
        }
    
        public virtual ObjectResult<GetUserOrders_Result> GetUserOrders(string uS_Name)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserOrders_Result>("GetUserOrders", uS_NameParameter);
        }
    
        public virtual ObjectResult<VendorOrders_Result> VendorOrders(string uS_Name)
        {
            var uS_NameParameter = uS_Name != null ?
                new ObjectParameter("US_Name", uS_Name) :
                new ObjectParameter("US_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VendorOrders_Result>("VendorOrders", uS_NameParameter);
        }
    
        public virtual ObjectResult<VendorOrderDetails_Result> VendorOrderDetails(string vendorName, Nullable<int> orderID)
        {
            var vendorNameParameter = vendorName != null ?
                new ObjectParameter("VendorName", vendorName) :
                new ObjectParameter("VendorName", typeof(string));
    
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VendorOrderDetails_Result>("VendorOrderDetails", vendorNameParameter, orderIDParameter);
        }
    }
}
