//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypOnEF.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pets_C1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pets_C1()
        {
            this.Pets_C3 = new HashSet<Pets_C3>();
            this.Product_C2 = new HashSet<Product_C2>();
        }
    
        public int PetsC1_Id { get; set; }
        public string PetsC1_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pets_C3> Pets_C3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_C2> Product_C2 { get; set; }
    }
}
