//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypOnEF.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pets_Warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pets_Warehouse()
        {
            this.Pets_Inventory = new HashSet<Pets_Inventory>();
        }
    
        public int PetsWarehouse_Id { get; set; }
        public string Descrption { get; set; }
        public int Cost { get; set; }
        public string Pets_Status { get; set; }
        public Nullable<int> ApprovedPets { get; set; }
        public Nullable<int> NotApprovedPets { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pets_Inventory> Pets_Inventory { get; set; }
    }
}
