//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypOnEF.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Inventory()
        {
            this.Vendor_Product = new HashSet<Vendor_Product>();
        }
    
        public int PI_Id { get; set; }
        public Nullable<int> PC3_Id { get; set; }
        public Nullable<int> VI_Id { get; set; }
        public Nullable<int> PI_OutOfStock { get; set; }
    
        public virtual Product_C3 Product_C3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_Product> Vendor_Product { get; set; }
        public virtual Vendor_Info Vendor_Info { get; set; }
    }
}
