//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypOnEF.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Info()
        {
            this.Blogs = new HashSet<Blog>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Pets_Inventory = new HashSet<Pets_Inventory>();
            this.Vendor_Info = new HashSet<Vendor_Info>();
        }
    
        public int US_Id { get; set; }
        public string US_Name { get; set; }
        public string US_Phone { get; set; }
        public string US_Address { get; set; }
        public string US_Email { get; set; }
        public Nullable<int> U_Id { get; set; }
        public string US_Password { get; set; }
        public Nullable<int> IsValid { get; set; }
        public string US_ConfirmCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blog> Blogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pets_Inventory> Pets_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_Info> Vendor_Info { get; set; }
        public virtual User_Type User_Type { get; set; }
    }
}
