//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FypOnEF.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Product_Qty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor_Product_Qty()
        {
            this.Vendor_Product_Cost = new HashSet<Vendor_Product_Cost>();
        }
    
        public int VPQ_Id { get; set; }
        public Nullable<int> VP_Id { get; set; }
        public Nullable<int> VPQ_Qty { get; set; }
        public Nullable<int> VPQ_Status { get; set; }
        public Nullable<int> VPQ_RemainingQty { get; set; }
    
        public virtual Vendor_Product Vendor_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_Product_Cost> Vendor_Product_Cost { get; set; }
    }
}
