//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Blog_Id { get; set; }
        public string Blog_Title { get; set; }
        public Nullable<System.DateTime> Blog_Date { get; set; }
        public string Blogger_PicturePath { get; set; }
        public string Blog_PicturePath { get; set; }
        public string Blog_WholeBlog { get; set; }
        public Nullable<int> US_Id { get; set; }
        public string Blogger_PictureName { get; set; }
        public string Blog_PictureName { get; set; }
        public Nullable<int> Blog_Status { get; set; }
    
        public virtual User_Info User_Info { get; set; }
    }
}
