//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_C3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_C3()
        {
            this.Product_Inventory = new HashSet<Product_Inventory>();
        }
    
        public int PC3_Id { get; set; }
        public string PC3_Name { get; set; }
        public Nullable<int> PC2_Id { get; set; }
        public Nullable<int> PC1_Id { get; set; }
        public Nullable<int> ProImg_Id { get; set; }
        public Nullable<int> Pro_Views { get; set; }
    
        public virtual Product_C1 Product_C1 { get; set; }
        public virtual Product_C2 Product_C2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Inventory> Product_Inventory { get; set; }
        public virtual Product_Image Product_Image { get; set; }
    }
}
