//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Inverntory_Sales
    {
        public int PIS_Id { get; set; }
        public int VP_Id { get; set; }
        public decimal PIS_SalesPrice { get; set; }
        public decimal PIS_CompanyPrice { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.DateTime FromDate { get; set; }
    
        public virtual Vendor_Product Vendor_Product { get; set; }
    }
}
