//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor_Product()
        {
            this.Product_Inverntory_Sales = new HashSet<Product_Inverntory_Sales>();
            this.Vendor_Product_Qty = new HashSet<Vendor_Product_Qty>();
        }
    
        public int VP_Id { get; set; }
        public Nullable<int> VP_ApproveProduct { get; set; }
        public string VP_Desc { get; set; }
        public string VP_Specs { get; set; }
        public Nullable<int> PI_Id { get; set; }
        public Nullable<int> VP_NotApproveProduct { get; set; }
    
        public virtual Product_Inventory Product_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Inverntory_Sales> Product_Inverntory_Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_Product_Qty> Vendor_Product_Qty { get; set; }
    }
}
